name: 'CI/CD'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' 
        cache: 'npm'
        cache-dependency-path: 'secondChance-backend/package-lock.json'

    - name: Install Dependencies and Run Linter
      working-directory: ./secondChance-backend 
      run: |
        npm install
        npm run lint
        echo "Linted all the js files successfully"